version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  dev:
    desc: Start Tauri development server with hot reload
    cmds:
      - pnpm run tauri dev

  dev:web:
    desc: Start Vite dev server only (no Tauri window)
    cmds:
      - pnpm run dev

  check:
    desc: Run all checks (lint, type-check, test)
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  lint:
    desc: Run ESLint on src/
    cmds:
      - pnpm run lint

  lint:fix:
    desc: Run ESLint with auto-fix
    cmds:
      - pnpm exec eslint src/ --fix

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - pnpm exec tsc --noEmit

  test:
    desc: Run tests once
    cmds:
      - pnpm test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - pnpm exec vitest

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - pnpm exec vitest run --coverage

  bundle:
    desc: Build the Tauri application for the current platform
    cmds:
      - pnpm run tauri build

  build:
    desc: Build the Tauri application for the current platform as a binary
    cmds:
      - pnpm run tauri build --no-bundle

  build:web:
    desc: Build the frontend only
    cmds:
      - pnpm run build

  build:debug:
    desc: Build the Tauri application in debug mode
    cmds:
      - pnpm run tauri build -- --debug

  build:flatpak:
    desc: Build Tauri app then package as Flatpak bundle
    deps:
      - build
    preconditions:
      - sh: command -v flatpak-builder
        msg: flatpak-builder is required. Install with 'sudo apt install flatpak-builder'
      - sh: command -v patchelf || nix-shell -p patchelf --run "which patchelf"
        msg: patchelf is required. Install with 'sudo apt install patchelf' or use devenv shell (includes patchelf via Nix)
    generates:
      - flatpak/openapi-editor.flatpak
      - flatpak/repo
    cmds:
      - cp src-tauri/target/release/openapi-editor flatpak/openapi-editor
      - nix-shell -p patchelf --run "patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 flatpak/openapi-editor"
      - cp src-tauri/icons/128x128.png flatpak/icon-128x128.png
      - cp src-tauri/icons/128x128@2x.png flatpak/icon-256x256.png
      - flatpak-builder --force-clean --disable-rofiles-fuse --repo=flatpak/repo flatpak/build flatpak/dev.brunopaz.openapi-editor.yml
      - flatpak build-bundle flatpak/repo flatpak/openapi-editor.flatpak dev.brunopaz.openapi-editor

  flatpak:install:
    desc: Installs the Flatpak bundle
    cmds:
      - flatpak install flatpak/openapi-editor.flatpak

  icons:
    desc: Regenerate app icons from SVG source
    deps:
      - icons:render
    cmds:
      - pnpm exec tauri icon /tmp/openapi-icon-1024.png

  icons:render:
    desc: Render icon SVG to 1024x1024 PNG (requires Inkscape)
    cmds:
      - inkscape --export-type=png --export-filename=/tmp/openapi-icon-1024.png --export-width=1024 --export-height=1024 src-tauri/icons/icon.svg
    preconditions:
      - sh: command -v inkscape
        msg: Inkscape is required to render the SVG icon

  install:
    desc: Install all dependencies (pnpm + cargo)
    cmds:
      - pnpm install --frozen-lockfile
      - cargo fetch --manifest-path src-tauri/Cargo.toml

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf dist
      - rm -rf src-tauri/target

  clean:node:
    desc: Remove node_modules and reinstall
    cmds:
      - rm -rf node_modules
      - pnpm install --frozen-lockfile
